#!/usr/bin/perl

use strict;
use warnings;

$|++;

my $graph = {};

while (<>) {
    chomp;
    my($from, @to) = split /\s+/;
    chop $from;
    for my $to (@to) {
        ++$graph->{$from}{$to};
    }
}

use Data::Dumper; print Dumper($graph), "\n";

my @queue = (["you", []]);
my %seen;
my %paths;

while (@queue) {
    my $node = shift @queue;
    my($curr, $path) = @{ $node };
    print "curr = $curr, path = [", join(", ", @{ $path }), "]\n";
    ++$paths{join "->", @{ $path }} if $curr eq "out";
    # next if $seen{$curr}++;
    for my $next (sort keys %{ $graph->{$curr} }) {
        push @queue, [ $next, [ @{ $path }, $next ] ];
    }
    use Data::Dumper; print Dumper(\@queue), "\n";
}

my @paths = sort keys %paths;

print "\n", join("\n", @paths), "\n\n";

print scalar(@paths), "\n\n";
