#!/usr/bin/perl

use strict;
use warnings;

chomp(my $input = <STDIN>);

my @chunks = split /,/, $input;

my $sum = 0;
my $max = 0;

for my $chunk (@chunks) {
    my($start, $end) = split /-/, $chunk;

    $max = length($start) if length($start) > $max;
    $max = length($end) if length($end) > $max;

    for (my $idx = $start; $idx <= $end; $idx++) {
        $sum += check($idx);
    }
}

print "\nsum = $sum with a max digit length of $max\n\n";

sub check {
    my($v) = @_;

    # Max number of digits is 10.

    if ($v =~ m{^0}) {
        $v =~ s{^0+}{};
        return $v;
    }

    return $v if $v =~ m{^(.+)\1+$};

    return 0;
}
