#!//usr/bin/perl

use strict;
use warnings;

my @tiles;

while (<>) {
    chomp;
    push @tiles, [ split /,/ ];
}

my @options;

for (my $idx = 0; $idx < @tiles - 1; $idx++) {
    for (my $jdx = $idx + 1; $jdx < @tiles; $jdx++) {
        my $area = area($tiles[$idx], $tiles[$jdx]);
        push @options, { AREA => $area, CORNER1 => $tiles[$idx], CORNER2 => $tiles[$jdx] };
    }
}

@options = sort { $b->{AREA} <=> $a->{AREA} } @options;

print "\n", $options[0]->{AREA}, "\n\n";

sub area {
    my($a, $b) = @_;
    return (1 + abs($a->[0] - $b->[0])) * (1 + abs($a->[1] - $b->[1]));
}

sub abs {
    my($v) = @_;
    return ($v >= 0) ? $v : -$v;
}
