#!/usr/bin/perl

use strict;
use warnings;

# Not sure why this works for the puzzle input, but not the sample...
# And really, it assumes complete packability/morphability, which
# seems wrong.  I'll take the gold star, though.

my %shape;
my $shape_idx;
my $total = 0;

while (<>) {
    chomp;

    if (m{^(\d+):$}) {
        $shape_idx = $1;
        $shape{$shape_idx} = 0;
    } elsif (m{#}) {
        s/\.//g;
        $shape{$shape_idx} += length;
    } elsif (m{^(\d+)x(\d+): (.+)$}) {
        my($w, $h, $other) = ($1, $2, $3);
        my @shapes = split /\s+/, $other;
        my $needed = 0;
        for (my $idx = 0; $idx < @shapes; $idx++) {
            $needed += $shapes[$idx] * $shape{$idx};
        }
        ++$total if $needed <= $w * $h;
    }
}

print "\n", $total, "\n\n";
